import React from 'react'
import Donation from '../pages/homepage/Donation'
import KuryemDonation from '../pages/homepage/KuryemDonation';



export const metadata = {
  title: "Donation | FX-References",
  description: "Generated by create next app",
};

export default function page() {
  return (
    <div>
        {/* <Donation/> */}
        <KuryemDonation/>
    </div>
  )
}
