import Register from '@/components/authanticaiton/Register'
import React from 'react'



export const metadata = {
  title: "Register | FX-References",
  description: "Generated by create next app",
};
export default function page({params}) {

  const {email} = params
  return (
    <div>
        <Register email={email}/>
    </div>
  )
}
