import React from 'react'
import Random from '../pages/homepage/Random'


export const metadata = {
  title: "Random | FX-References",
  description: "Generated by create next app",
};

export default function page() {
  return (
    <div>
    
    
<Random/>
    </div>
  )
}
