import SignIn from '@/components/authanticaiton/SignIn'
import React from 'react'



export const metadata = {
  title: "Sign-in | FX-References",
  description: "Generated by create next app",
};

export default function page() {
  return (
    <div>
        <SignIn/>
    </div>
  )
}
