import AddShot from '@/components/admin/AddShot'
import React from 'react'

export const metadata = {
  title: "Add Shot | FX-References",
  description: "Generated by create next app",
};
export default function page() {
  return (
    <div>
        <AddShot/>
    </div>
  )
}
