import Verification from '@/components/authanticaiton/Verification'
import React from 'react'



export const metadata = {
  title: "Verification | FX-References",
  description: "Generated by create next app",
};
export default function page({params}) {

    const {email} = params;
  return (
    <div>
        
        <Verification email={email}/>
    </div>
  )
}
