import MyCollection from '@/components/homepage/MyCollection'
import React from 'react'

export const metadata = {
  title: "My Collection | FX-References",
  description: "Generated by create next app",
};
export default function page() {
  return (
    <div>
        <MyCollection/>
    </div>
  )
}
