import SignUp from '@/components/admin/SignUp'
import React from 'react'

export const metadata = {
  title: "Sign-Up | FX-References",
  description: "Generated by create next app",
};

export default function page() {
  return (
    <div>
        <SignUp/>
    </div>
  )
}




