import Browse from '@/app/pages/homepage/Browse';
import React from 'react'

export const metadata = {
  title: "Browse | FX-References",
  description: "Generated by create next app",
};

export default function page({params}) {
    const search = params?.search;
  return (
    <div className=''>
        <Browse search={search}/>
    </div>
  )
}


