import React from 'react'
import Browse from '../pages/homepage/Browse'


export const metadata = {
  title: "Browse | FX-References",
  description: "Generated by create next app",
};

export default function page() {
  return (
    <div>
        <Browse/>
    </div>
  )
}
