import AddShot from '@/components/admin/AddShot'
import React from 'react'



export const metadata = {
  title: "Add Shot | FX-References",
  description: "Generated by create next app",
};
export default function page() {

  
  return (
    <div className='flex items-center my-auto'>



        <AddShot/>
    </div>
  )
}







