

import MySHot from '@/components/homepage/MyShot'
import React from 'react'

export const metadata = {
  title: "My Shot | FX-References",
  description: "Generated by create next app",
};

export default function page() {
  return (
    <div className='pt-16'>
        
<MySHot/>
    </div>
  )
}
